%
(Header)
(Generated by gcodetools from Inkscape.)
(Using default header. To add your own header create file "header" in the output dir.)
M3
(Header end.)
G20 (All units in inches)

(Start cutting path id: path328)
(Change tool to Cylindrical cutter)

G00 Z5.000000
G00 X10.937125 Y1.643314

G01 Z-1.000000 F100.0(Penetrate)
G03 X10.884698 Y1.646297 Z-1.000000 I-0.157493 J-2.305665 F400.000000
G03 X10.617515 Y1.657856 Z-1.000000 I-2.712306 J-59.598937
G02 X10.350413 Y1.670615 Z-1.000000 I0.813317 J19.828141
G02 X10.235030 Y1.678711 Z-1.000000 I0.202132 J3.707203
G03 X10.119720 Y1.688089 Z-1.000000 I-1.105058 J-12.873153

%